rag:
 paths:
   output_json: '/pc_project/combined_ptt_mobile01_documents_all_ptt_smaller_v2.jsonl'
   embedding_data: '/pc_project/embedding_data.pkl'
 
 model:
   embedding_model: 'intfloat/multilingual-e5-large'
   llm_model: 'gpt-3.5-turbo'
   
 retrieval:
   top_k: 20
   score_threshold: 0.5

 prompt:
   system_prompt: "你是一個專業的電腦硬體推薦助手..."